name = "statikapi-cf-demo"
main = "dist/worker.mjs"
compatibility_date = "2025-01-01"

[[r2_buckets]]
binding = "STATIK_BUCKET"
bucket_name = "statikapi-json"

[[kv_namespaces]]
binding = "REPLACE_ME_WITH_MANIFEST_BINDING"
id = "REPLACE_ME_WITH_KV_NAMESPACES_ID"

[vars]
STATIK_BUILD_TOKEN = "REPLACE_ME_WITH_BUILD_TOKEN"
STATIK_SRC = "src-api"
STATIK_USE_INDEX_JSON = "false"
STATIK_MANIFEST_BINDING = "REPLACE_ME_WITH_MANIFEST_BINDING"